### ISSUE TITLE
App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [jparyani/mediawiki-sandstorm#1]
@jparyani 

The larger graphics are from their website and I made them a vector mini grain icon. Thoughts? :)

![mediawiki-preview1](https://cloud.githubusercontent.com/assets/855341/9280914/69f851f2-4276-11e5-9cb9-11738d3a174f.png)

**Comment by jparyani** [comment]
LGTM

**Comment by ovizii** [comment]
Cute :-)
